/* Auto-generated by tools/wav_to_pwm.py — do not edit. */
/* Source: ES_Objects, Container, Cardboard Box, Package, Slide, Bang Into Others - Epidemic Sound.wav */
#ifndef AMB_SLIDE_H
#define AMB_SLIDE_H
#include <stdint.h>

#define AMB_SLIDE_SAMPLE_COUNT 9021
#define AMB_SLIDE_SAMPLE_RATE  8000
#define AMB_SLIDE_SAMPLE_BITS  8

extern const int8_t amb_slide_samples[9021];

#endif
