/* AUTO-GENERATED by tools/gen_assets.py from registry.json.
 * Community sprite palettes -> CRAM arena entries. Painted by
 * build_palette(); do NOT edit. */
#ifndef COMM_PAL_H
#define COMM_PAL_H

typedef struct { unsigned char idx, r, g, b; } comm_pal_t;
static const comm_pal_t comm_pal[] = {
    { 145, 17, 14, 10 },   /* desk [0] */
    { 146, 18, 15, 11 },   /* desk [1] */
    { 147, 21, 17, 13 },   /* desk [2] */
    { 148, 23, 19, 14 },   /* desk [3] */
    { 153, 25, 25, 21 },   /* torn [0] */
    { 154, 26, 25, 22 },   /* torn [1] */
    { 155, 26, 26, 22 },   /* torn [2] */
    { 156, 27, 26, 22 },   /* torn [3] */
    { 157, 27, 27, 23 },   /* torn [4] */
    { 158, 28, 28, 24 },   /* torn [5] */
    { 159, 30, 30, 25 },   /* torn [6] */
    { 161, 25, 24, 21 },   /* torn2 [0] */
    { 162, 25, 25, 21 },   /* torn2 [1] */
    { 163, 26, 26, 22 },   /* torn2 [2] */
    { 164, 27, 27, 23 },   /* torn2 [3] */
    { 165, 28, 27, 23 },   /* torn2 [4] */
    { 166, 29, 29, 25 },   /* torn2 [5] */
    { 169, 24, 24, 20 },   /* torn3 [0] */
    { 170, 26, 25, 22 },   /* torn3 [1] */
    { 171, 27, 26, 22 },   /* torn3 [2] */
    { 172, 28, 27, 23 },   /* torn3 [3] */
    { 173, 29, 29, 25 },   /* torn3 [4] */
    { 174, 30, 30, 26 },   /* torn3 [5] */
    { 175, 31, 30, 26 },   /* torn3 [6] */
    { 177, 16, 3, 3 },   /* iamgod [0] */
    { 178, 17, 3, 3 },   /* iamgod [1] */
    { 179, 18, 3, 4 },   /* iamgod [2] */
    { 185, 18, 0, 0 },   /* stopsign [0] */
    { 186, 19, 4, 4 },   /* stopsign [1] */
    { 187, 24, 23, 23 },   /* stopsign [2] */
    { 188, 25, 25, 25 },   /* stopsign [3] */
    { 189, 26, 26, 26 },   /* stopsign [4] */
    { 190, 27, 27, 27 },   /* stopsign [5] */
    { 191, 28, 29, 29 },   /* stopsign [6] */
    { 193, 0, 0, 0 },   /* crayonwin [0] */
};
#define COMM_PAL_COUNT 35

#endif
