/* AUTO-GENERATED by tools/gen_assets.py from registry.json.
 * Community sprite palettes -> CRAM arena entries. Painted by
 * build_palette(); do NOT edit. */
#ifndef COMM_PAL_H
#define COMM_PAL_H

typedef struct { unsigned char idx, r, g, b; } comm_pal_t;
static const comm_pal_t comm_pal[] = {
    { 0, 0, 0, 0 },   /* placeholder: keeps the array legal */
};
#define COMM_PAL_COUNT 0

#endif
