/* Auto-generated by tools/compose_desk_pvm.py — do not edit.
 * The desk bake with the PVM MONITOR (pvm3d.h box 0, no stand) seated
 * off-center on the desktop. Drawn under the PVM's world_h (0.4): desk
 * coords are scaled 0.775 to stay true-size, the monitor's scale factors
 * cancel to exactly 1. Box 0 = the monitor (carries pvm_front_tex).
 * Total model height 294 units = 0.459 cells. */
#ifndef DESK_PVM3D_H
#define DESK_PVM3D_H
#include <stdint.h>
#include "chair3d.h"

#define DESK_PVM_NBOXES 9

static const cbox_t desk_pvm_boxes[DESK_PVM_NBOXES] = {
    {   -146,   198,   -56,   -40,   294,    45 },
    {   -195,     0,   -87,   -76,   188,    92 },
    {     93,     0,   -96,   202,   188,    92 },
    {   -215,   188,   -96,  -146,   198,    92 },
    {   -146,   188,   -96,   -40,   198,    92 },
    {    -40,   188,   -96,   212,   198,    92 },
    {     30,   198,   -19,   150,   212,    19 },
    {     36,   212,   -15,   144,   223,    15 },
    {     46,   223,   -10,   134,   231,    10 },
};

#endif /* DESK_PVM3D_H */
