/* Auto-generated by tools/bake_boxes.py from sega_master_system.glb — do not edit.
 * 4 DISJOINT axis-aligned boxes covering 99.6% of the model volume.
 * Disjoint by construction (each box consumes its voxels), so the
 * renderer's centroid painter sort is exact — see chair3d.h. */
#ifndef SMS3D_H
#define SMS3D_H
#include <stdint.h>
#include "chair3d.h"        /* cbox_t, chair_face_v */

#define SMS_NBOXES 4

static const cbox_t sms_boxes[SMS_NBOXES] = {
    {   -41,     0,   -31,    39,   219,    33 },
    {   -31,   219,     1,    28,   251,    28 },
    {   -41,    43,   -36,    39,   128,   -31 },
    {   -31,   219,    -4,    33,   235,     1 },
};

#endif /* SMS3D_H */
