/* Auto-generated by tools/bake_boxes.py from sega_master_system.glb — do not edit.
 * 1 DISJOINT axis-aligned boxes covering 94.1% of the model volume.
 * Disjoint by construction (each box consumes its voxels), so the
 * renderer's centroid painter sort is exact — see chair3d.h. */
#ifndef SMS3D_H
#define SMS3D_H
#include <stdint.h>
#include "chair3d.h"        /* cbox_t, chair_face_v */

#define SMS_NBOXES 1

static const cbox_t sms_boxes[SMS_NBOXES] = {
    {   -41,     0,   -36,    44,   213,    39 },
};

#endif /* SMS3D_H */
