#!/usr/bin/env python3
"""Bake the directional chair billboard set from the IN-GAME box model.

Renders the 7-box chair (parsed live from sh_src/chair3d.h, so model edits
are picked up automatically) at N viewer poses with the engine's exact
transform math, quantizes to the door-brown ramp, and emits
sh_src/chair_dir_tex.h plus a validation strip PNG to eyeball BEFORE any
ROM build.

The workflow: pick a pose in the in-ROM asset viewer (GAME variant), read
the Y/X coordinates off the screen, and run:

    tools/bake_dir_sprites.py --pitch 246 --yaws 0,238,218,194,180,156,128

Yaws should cover the half circle 0..128 (front..back, uneven spacing is
fine); the engine's 12-sector picker mirrors them for the other half.
Values: 0 transparent, 1..5 -> DOOR_BASE+(v-1) via the sprite vmap (the
same fog-aware decode the in-game paint path uses).
"""
import argparse, math, os, re, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FACES = [((1,5,7,3),4),((0,2,6,4),4),((2,3,7,6),6),((0,4,5,1),2),
         ((4,6,7,5),3),((0,1,3,2),3)]   # corner-bit quads + chair_face_shade axsh


def load_boxes():
    """Parse chair_boxes[] out of chair3d.h: 7 lines of 6 CM(...) values in
    struct order x0,y0,z0,x1,y1,z1."""
    src = open(os.path.join(REPO, "sh_src/chair3d.h")).read()
    body = src.split("chair_boxes[")[1]
    boxes = []
    for m in re.finditer(r"\{([^}]*)\}", body):
        vals = re.findall(r"CM\(\s*(-?[0-9.]+)\s*\)", m.group(1))
        if len(vals) == 6:
            boxes.append(tuple(float(v) for v in vals))
    if not boxes:
        sys.exit("no chair_boxes parsed from chair3d.h")
    return boxes


def build_mesh(boxes):
    verts, tris = [], []
    for (x0, y0, z0, x1, y1, z1) in boxes:
        base = len(verts)
        for v in range(8):
            verts.append((x1 if v & 1 else x0,
                          y1 if v & 2 else y0,
                          z1 if v & 4 else z0))
        for (c, s) in FACES:
            tris.append((base+c[0], base+c[1], base+c[2], s))
            tris.append((base+c[0], base+c[2], base+c[3], s))
    return verts, tris


def render_idx(verts, tris, rotY, rotX, big=448):
    """Ramp-index image: 0 transparent, 1..5 = door ramp index+1. Same
    yaw/pitch/ortho/painter math as raycast_model_view."""
    from PIL import Image, ImageDraw
    th = rotY*2*math.pi/256; ph = rotX*2*math.pi/256
    cy, sy = math.cos(th), math.sin(th); cx, sx = math.cos(ph), math.sin(ph)
    img = Image.new('L', (big, big), 0); d = ImageDraw.Draw(img)
    ZOOM = big*0.62
    P, Z = [], []
    for (x, y, z) in verts:
        y -= 0.5
        x1 = x*cy + z*sy; z1 = -x*sy + z*cy
        y2 = y*cx - z1*sx; z2 = y*sx + z1*cx
        P.append((big/2 + x1*ZOOM, big/2 - y2*ZOOM)); Z.append(z2)
    for t in sorted(range(len(tris)), key=lambda t: -(Z[tris[t][0]]+Z[tris[t][1]]+Z[tris[t][2]])):
        a, b, c, s = tris[t]
        r = max(0, min(4, (s-1)*5//7))
        d.polygon([P[a], P[b], P[c]], fill=r+1)
    return img


def main():
    from PIL import Image, ImageDraw
    ap = argparse.ArgumentParser()
    ap.add_argument("--yaws", default="0,238,218,194,180,156,128",
                    help="comma list of model yaws (engine 0..255), front..back half circle")
    ap.add_argument("--pitch", type=int, default=246, help="camera pitch (engine 0..255)")
    ap.add_argument("--height", type=int, default=56, help="sprite height in pixels")
    ap.add_argument("--out", default="sh_src/chair_dir_tex.h")
    ap.add_argument("--strip", default="", help="optional validation strip PNG path")
    args = ap.parse_args()
    yaws = [int(y) & 255 for y in args.yaws.split(",")]
    H = args.height

    verts, tris = build_mesh(load_boxes())
    views = []
    for yw in yaws:
        im = render_idx(verts, tris, yw, args.pitch)
        im = im.crop(im.getbbox())
        w = max(1, round(H*im.width/im.height))
        views.append((yw, w, im.resize((w, H), Image.NEAREST)))

    out = os.path.join(REPO, args.out)
    with open(out, "w") as f:
        f.write("/* Auto-generated by tools/bake_dir_sprites.py from the in-game box model\n")
        f.write(" * (sh_src/chair3d.h). Poses: pitch %d, yaws %s. Do not edit.\n" % (args.pitch, yaws))
        f.write(" * Values: 0 transparent, 1..5 -> DOOR_BASE+(v-1) via the sprite vmap\n")
        f.write(" * (distance fog applies). ROW-MAJOR tex[y][x]; X-mirror covers the\n")
        f.write(" * other half circle in the engine's 12-sector picker. */\n")
        f.write("#ifndef CHAIR_DIR_TEX_H_INCLUDED\n#define CHAIR_DIR_TEX_H_INCLUDED\n#include <stdint.h>\n\n")
        f.write("#define CHAIR_DIR_VIEWS  %d\n#define CHAIR_DIR_H      %d\n\n" % (len(views), H))
        for i, (yw, w, im) in enumerate(views):
            f.write("/* view %d: model yaw %d */\n" % (i, yw))
            f.write("#define CHAIR_DIR_W%d %d\n" % (i, w))
            f.write("static const uint8_t chair_dir_tex%d[CHAIR_DIR_H][%d] = {\n" % (i, w))
            for y in range(H):
                f.write("    {" + ",".join(str(im.getpixel((x, y))) for x in range(w)) + "},\n")
            f.write("};\n\n")
        f.write("typedef struct { const uint8_t *tex; uint8_t w; } chair_dir_view_t;\n")
        f.write("static const chair_dir_view_t chair_dir_views[CHAIR_DIR_VIEWS] = {\n")
        for i, (yw, w, im) in enumerate(views):
            f.write("    { (const uint8_t*)chair_dir_tex%d, CHAIR_DIR_W%d },\n" % (i, i))
        f.write("};\n\n")

        # Sector tables: every baked yaw is a direct sector; every non-self-mirror
        # yaw also serves its reflection (256-yaw) with texX reversed. The engine
        # picker just argmaxes dot products over these — view count is data.
        sectors = [(yw % 256, i, 0) for i, (yw, w, im) in enumerate(views)]
        for i, (yw, w, im) in enumerate(views):
            m = (256 - yw) % 256
            if m != yw % 256:
                sectors.append((m, i, 1))
        sectors.sort()
        f.write("/* Bearing sectors: normalized view yaw, sprite index, mirror flag.\n")
        f.write(" * The picker maximizes dot(chair->player, dir(facing+128+v)). */\n")
        f.write("#define CHAIR_DIR_SECTORS %d\n" % len(sectors))
        f.write("static const uint8_t chair_dir_sect_v[CHAIR_DIR_SECTORS] = {\n    %s };\n"
                % ",".join(str(v) for v, s, m in sectors))
        f.write("static const uint8_t chair_dir_sect_view[CHAIR_DIR_SECTORS] = {\n    %s };\n"
                % ",".join(str(s) for v, s, m in sectors))
        f.write("static const uint8_t chair_dir_sect_mirror[CHAIR_DIR_SECTORS] = {\n    %s };\n"
                % ",".join(str(m) for v, s, m in sectors))
        f.write("\n#endif\n")
    print("wrote %s  views: %s" % (args.out, [(yw, w) for yw, w, _ in views]))

    if args.strip:
        DOOR = [(15*8,12*8,9*8),(18*8,15*8,11*8),(22*8,18*8,14*8),(25*8,21*8,16*8),(29*8,25*8,20*8)]
        sc = 4
        tot = sum(w for _, w, _ in views)
        sheet = Image.new('RGB', ((tot+len(views)*3)*sc, H*sc+16), (40, 40, 44))
        dd = ImageDraw.Draw(sheet)
        x0 = 0
        for yw, w, im in views:
            for y in range(H):
                for x in range(w):
                    v = im.getpixel((x, y))
                    if v:
                        for dy in range(sc):
                            for dx in range(sc):
                                sheet.putpixel((x0+x*sc+dx, y*sc+dy), DOOR[v-1])
            dd.text((x0, H*sc+2), str(yw), fill=(255, 230, 0))
            x0 += (w+3)*sc
        sheet.save(args.strip)
        print("wrote strip:", args.strip)


if __name__ == "__main__":
    main()
