#!/usr/bin/env python3
"""Bake the chair's floor-shadow stencils from the in-game box model.

A chair shadow from a ceiling light is the PLAN silhouette sheared along the
cast direction: every model point (x, y, z) lands on the floor at
(x, z + y*k) — taller parts throw farther. Three shear factors give a
short/medium/long series. The stencil's v=0 row IS the near feet line
(model z = -0.26), so the engine anchors it on the light-side feet and
contact is guaranteed by construction, not by tuned constants.

Emits sh_src/chair_shadow_tex.h: per-variant stencils (1 = shadow texel,
0 = empty, ROW-MAJOR tex[v][u]) plus world-space placement metadata in
16.16 fx derived from CHAIR_WORLD_H_FX scaling. Run with --strip to eyeball
the shapes before any ROM build.
"""
import argparse, math, os, re, sys
from PIL import Image, ImageDraw

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORLD_SCALE = 0.375           # CHAIR_WORLD_H_FX: model height 1.0 -> world cells
FX = lambda v: round(v * 65536)


def load_boxes():
    src = open(os.path.join(REPO, "sh_src/chair3d.h")).read()
    body = src.split("chair_boxes[")[1]
    out = []
    for m in re.finditer(r"\{([^}]*)\}", body):
        vals = re.findall(r"CM\(\s*(-?[0-9.]+)\s*\)", m.group(1))
        if len(vals) == 6:
            out.append(tuple(float(v) for v in vals))   # x0,y0,z0,x1,y1,z1
    if not out:
        sys.exit("no chair_boxes parsed")
    return out


FACES = [(0,1,3,2),(4,5,7,6),(0,1,5,4),(2,3,7,6),(0,2,6,4),(1,3,7,5)]

def bake(k, W=40, hires=280):
    """Silhouette for shear factor k. Model x lateral, w = z + y*k cast axis."""
    boxes = load_boxes()
    x_lo, x_hi = -0.26, 0.26
    w_lo = -0.26                      # near feet line (legs at z=-0.26, y=0)
    w_hi = 0.26 + k                   # back posts (z=0.26, y=1.0) thrown k
    sx = hires / (x_hi - x_lo)
    sw = 1                            # keep aspect: same scale both axes
    H = max(1, round(hires * (w_hi - w_lo) / (x_hi - x_lo)))
    swl = H / (w_hi - w_lo)
    img = Image.new('1', (hires, H), 0)
    d = ImageDraw.Draw(img)
    for (x0, y0, z0, x1, y1, z1) in boxes:
        pts = []
        for c in range(8):
            x = x1 if c & 1 else x0
            y = y1 if c & 2 else y0
            z = z1 if c & 4 else z0
            u = (x - x_lo) * sx
            v = ((z + y * k) - w_lo) * swl
            pts.append((u, v))
        for f in FACES:                       # union of projected faces = silhouette
            d.polygon([pts[i] for i in f], fill=1)
    Hs = max(1, round(W * H / hires))
    small = img.resize((W, Hs), Image.BOX)    # BOX downsample: any coverage -> gray
    grid = [[1 if small.getpixel((u, v)) else 0 for u in range(W)] for v in range(Hs)]
    meta = {
        "anchor_fx": FX(0.26 * WORLD_SCALE),          # center -> near feet line, along -light
        "len_fx":    FX((w_hi - w_lo) * WORLD_SCALE), # stencil world length along +cast
        "width_fx":  FX((x_hi - x_lo) * WORLD_SCALE), # stencil world width (lateral)
    }
    return grid, W, Hs, meta


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--shears", default="0.5,0.9,1.4", help="short,medium,long")
    ap.add_argument("--width", type=int, default=40)
    ap.add_argument("--strip", default="")
    args = ap.parse_args()
    ks = [float(s) for s in args.shears.split(",")]
    names = ["SHORT", "MED", "LONG"][:len(ks)]
    variants = [bake(k, args.width) for k in ks]

    out = os.path.join(REPO, "sh_src/chair_shadow_tex.h")
    with open(out, "w") as f:
        f.write("/* Auto-generated by tools/bake_chair_shadow.py from the box model\n")
        f.write(" * (sh_src/chair3d.h). Plan silhouette sheared along the cast axis;\n")
        f.write(" * v=0 row IS the near feet line — anchor it on the light-side feet\n")
        f.write(" * and leg contact is constructional. shears=%s. Do not edit. */\n" % ks)
        f.write("#ifndef CHAIR_SHADOW_TEX_H\n#define CHAIR_SHADOW_TEX_H\n#include <stdint.h>\n\n")
        f.write("#define CHAIR_SHADOW_VARIANTS %d\n" % len(ks))
        for i, ((grid, W, Hs, meta), nm) in enumerate(zip(variants, names)):
            f.write("/* %s: shear %.2f, %dx%d */\n" % (nm, ks[i], W, Hs))
            f.write("#define CHAIR_SHADOW_W%d %d\n#define CHAIR_SHADOW_H%d %d\n" % (i, W, i, Hs))
            f.write("static const uint8_t chair_shadow%d[%d][%d] = {\n" % (i, Hs, W))
            for row in grid:
                f.write("    {" + ",".join(str(v) for v in row) + "},\n")
            f.write("};\n")
        f.write("\ntypedef struct { const uint8_t *tex; uint8_t w, h;\n")
        f.write("                 int32_t anchor_fx, len_fx, width_fx; } chair_shadow_t;\n")
        f.write("static const chair_shadow_t chair_shadows[CHAIR_SHADOW_VARIANTS] = {\n")
        for i, ((grid, W, Hs, meta), nm) in enumerate(zip(variants, names)):
            f.write("    { (const uint8_t*)chair_shadow%d, %d, %d, %d, %d, %d },\n"
                    % (i, W, Hs, meta["anchor_fx"], meta["len_fx"], meta["width_fx"]))
        f.write("};\n\n#endif\n")
    print("wrote sh_src/chair_shadow_tex.h:",
          ", ".join("%s %dx%d" % (nm, v[1], v[2]) for v, nm in zip(variants, names)))

    if args.strip:
        pad = 8
        cells = [(v[1], v[2]) for v in variants]
        sc = 5
        tot_w = sum(w for w, h in cells) * sc + pad * (len(cells) + 1)
        max_h = max(h for w, h in cells) * sc + 30
        sheet = Image.new('RGB', (tot_w, max_h), (40, 40, 44))
        dd = ImageDraw.Draw(sheet)
        x0 = pad
        for (grid, W, Hs, meta), nm in zip(variants, names):
            for v in range(Hs):
                for u in range(W):
                    if grid[v][u] and (u ^ v) & 1:      # preview the 50% dither
                        for dy in range(sc):
                            for dx in range(sc):
                                sheet.putpixel((x0 + u*sc + dx, 12 + v*sc + dy), (60, 48, 36))
            dd.line([(x0, 12), (x0 + W*sc, 12)], fill=(255, 230, 0))  # feet/anchor line
            dd.text((x0, max_h - 14), "%s (feet line in yellow)" % nm, fill=(200, 200, 200))
            x0 += W * sc + pad
        sheet.save(args.strip)
        print("wrote strip:", args.strip)


if __name__ == "__main__":
    main()
