#!/usr/bin/env python3
"""Bake a GLB/glTF model into a fixed-point tri-mesh header for the live
sprite renderer (chair3d.c). Headless Blender, same family as export_box.py:

    blender --background --python tools/bake_model.py -- \
        models/chair.glb sh_src/chair_model.h [target_tris]

What it does:
  - imports the model, joins all meshes, applies transforms
  - Decimates to <= target_tris (default 240) — the SH-2 rasterizes this
    every frame, keep it lean
  - normalizes: feet at y=0, height = 1.0 model unit, centred in x/z,
    Blender Z-up -> engine Y-up
  - per-face shade 1..7: material base-color luminance (3 levels) modulated
    by a fixed model-space light on the face normal (form cue), so single-
    material models still read as 3D
  - emits CHAIRM_* tables: int16 verts (8.8), uint16 tri indices + uint8
    shade. chair3d.c picks the header up via __has_include and swaps its
    built-in box chair for the baked mesh.
"""
import bpy, sys, math
from mathutils import Vector

argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
if len(argv) < 2:
    print("usage: blender --background --python tools/bake_model.py -- "
          "in.glb out.h [target_tris]"); sys.exit(1)
SRC, OUT = argv[0], argv[1]
TARGET = int(argv[2]) if len(argv) > 2 else 240

bpy.ops.wm.read_factory_settings(use_empty=True)
bpy.ops.import_scene.gltf(filepath=SRC)

# Join every mesh into one object with world transforms applied.
meshes = [o for o in bpy.context.scene.objects if o.type == 'MESH']
if not meshes:
    print("no meshes in", SRC); sys.exit(1)
bpy.ops.object.select_all(action='DESELECT')
for o in meshes:
    o.select_set(True)
bpy.context.view_layer.objects.active = meshes[0]
if len(meshes) > 1:
    bpy.ops.object.join()
obj = bpy.context.view_layer.objects.active
bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)

# Triangulate, then decimate down to the budget.
tri_mod = obj.modifiers.new("tri", 'TRIANGULATE')
bpy.ops.object.modifier_apply(modifier=tri_mod.name)
ntris = len(obj.data.polygons)
if ntris > TARGET:
    dec = obj.modifiers.new("dec", 'DECIMATE')
    dec.ratio = TARGET / ntris
    bpy.ops.object.modifier_apply(modifier=dec.name)
    # Decimate can leave n-gons; re-triangulate.
    tri2 = obj.modifiers.new("tri2", 'TRIANGULATE')
    bpy.ops.object.modifier_apply(modifier=tri2.name)
me = obj.data
print(f"baked tris: {len(me.polygons)} (from {ntris}), verts: {len(me.vertices)}")

# Normalize: Blender Z-up -> engine Y-up (ex, ey, ez) = (x, z, -y);
# feet at y=0, height 1.0, centred in x/z.
vs = [Vector((v.co.x, v.co.z, -v.co.y)) for v in me.vertices]
mn = Vector((min(v.x for v in vs), min(v.y for v in vs), min(v.z for v in vs)))
mx = Vector((max(v.x for v in vs), max(v.y for v in vs), max(v.z for v in vs)))
h = mx.y - mn.y or 1.0
cx, cz = (mn.x + mx.x) / 2, (mn.z + mx.z) / 2
vs = [Vector(((v.x - cx) / h, (v.y - mn.y) / h, (v.z - cz) / h)) for v in vs]

# Per-material base shade (1..7 ramp): luminance of base color -> 3 bands.
def mat_lum(mi):
    try:
        m = me.materials[mi]
        c = m.node_tree.nodes["Principled BSDF"].inputs["Base Color"].default_value
        return 0.299 * c[0] + 0.587 * c[1] + 0.114 * c[2]
    except Exception:
        return 0.6

LIGHT = Vector((-0.5, 0.7, -0.5)).normalized()   # model-space, upper front-left
tris = []
for p in me.polygons:
    if len(p.vertices) != 3:
        continue
    # engine-space normal from the transformed verts
    a, b, c = (vs[i] for i in p.vertices)
    n = (b - a).cross(c - a)
    n = n.normalized() if n.length > 1e-9 else Vector((0, 1, 0))
    base = 3 + round(mat_lum(p.material_index) * 3)       # 3..6
    mod = n.dot(LIGHT)                                     # -1..1
    s = max(1, min(7, base + round(mod * 2)))
    tris.append((p.vertices[0], p.vertices[1], p.vertices[2], s))

with open(OUT, "w") as f:
    f.write("/* Auto-generated by tools/bake_model.py from %s — do not edit. */\n"
            % SRC.split("/")[-1])
    f.write("#ifndef CHAIR_MODEL_H\n#define CHAIR_MODEL_H\n#include <stdint.h>\n\n")
    f.write("#define CHAIRM_NVERTS %d\n#define CHAIRM_NTRIS  %d\n\n"
            % (len(vs), len(tris)))
    f.write("static const int16_t chairm_verts[CHAIRM_NVERTS][3] = {  /* 8.8, y-up */\n")
    for v in vs:
        f.write("    { %d, %d, %d },\n"
                % (round(v.x * 256), round(v.y * 256), round(v.z * 256)))
    f.write("};\n\nstatic const uint16_t chairm_tri[CHAIRM_NTRIS][3] = {\n")
    for t in tris:
        f.write("    { %d, %d, %d },\n" % (t[0], t[1], t[2]))
    f.write("};\n\nstatic const uint8_t chairm_shade[CHAIRM_NTRIS] = {\n    ")
    f.write(", ".join(str(t[3]) for t in tris))
    f.write("\n};\n\n#endif /* CHAIR_MODEL_H */\n")
print("wrote", OUT)
