#!/usr/bin/env python3
"""Compose the desk-with-PVM box model from the two shipped bakes.

Monitor ONLY (pvm3d.h box 0 — the stand stays on the floor-model), seated
on the desk's desktop. Rendered under the PVM's world_h (0.4), so desk
coordinates scale by world_h_desk/world_h_pvm = 0.31/0.4 = 0.775 to keep
the desk at its true size; the monitor's own scale factors cancel exactly
(pvm->desk * desk->final = 0.4/0.31 * 0.31/0.4 = 1), so its coords carry
over unchanged, just translated onto the desktop.

Monitor sits OFF-CENTER (x -93 final units): reads as placed by a person,
not by a compiler. Random-position variants arrive with the second desk
item (one variant mechanism, designed once).
"""
import pathlib

T = 0.775                       # desk-unit -> final-unit (0.31 / 0.4)
DESK = [(-252, 0, -112, -98, 243, 119),
        (120, 0, -124, 260, 243, 119),
        (-277, 243, -124, 273, 256, 119)]
MON = (-53, 160, -55, 53, 256, 46)     # pvm3d.h box 0
MON_CX, MON_CZ = -93, -6               # placement on the desktop (final units)

desk_f = [tuple(round(v * T) for v in b) for b in DESK]
desk_top = max(b[4] for b in desk_f)                     # y of the desktop
mx0, my0, mz0, mx1, my1, mz1 = MON
mw2 = (mx1 - mx0) // 2
mzc = (mz0 + mz1) // 2
mon_f = (MON_CX - mw2, desk_top, mz0 - mzc + MON_CZ,
         MON_CX + mw2, desk_top + (my1 - my0), mz1 - mzc + MON_CZ)

out = pathlib.Path(__file__).resolve().parent.parent / "sh_src" / "desk_pvm3d.h"
boxes = [mon_f] + desk_f          # MONITOR FIRST: ftex binds to box 0 face 5
lines = "\n".join(f"    {{ {b[0]:6d},{b[1]:6d},{b[2]:6d},{b[3]:6d},{b[4]:6d},{b[5]:6d} }},"
                  for b in boxes)
out.write_text(f"""/* Auto-generated by tools/compose_desk_pvm.py — do not edit.
 * The desk bake with the PVM MONITOR (pvm3d.h box 0, no stand) seated
 * off-center on the desktop. Drawn under the PVM's world_h (0.4): desk
 * coords are scaled 0.775 to stay true-size, the monitor's scale factors
 * cancel to exactly 1. Box 0 = the monitor (carries pvm_front_tex).
 * Total model height {mon_f[4]} units = {mon_f[4]/256*0.4:.3f} cells. */
#ifndef DESK_PVM3D_H
#define DESK_PVM3D_H
#include <stdint.h>
#include "chair3d.h"

#define DESK_PVM_NBOXES {len(boxes)}

static const cbox_t desk_pvm_boxes[DESK_PVM_NBOXES] = {{
{lines}
}};

#endif /* DESK_PVM3D_H */
""")
print(f"wrote {out}: monitor {mon_f}, model top y={mon_f[4]}")
