#!/usr/bin/env python3
"""SMS mini-game blob packager.

Reads sms/game.bin (the wla-z80 output: an 8KB image that executes from
Z80 RAM) and emits md_src/z80_sms_game.h for the 68K side. The contract
addresses (TILEBUF, MAP_BITS, mailboxes...) are parsed straight out of
game.asm's .DEFINE lines so the asm stays the single source of truth —
a drifted hand-copied constant here is exactly the kind of bug that ate
a week of grey menus.

The upload length is trimmed to the last nonzero byte (the image's tail
is .EMPTYFILL zeros covering TILEBUF/MAP space the 68K writes itself),
then rounded up to even. The blob must stay below TILEBUF: everything
at TILEBUF and above belongs to runtime data the 68K or Z80 owns.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASM = ROOT / "sms" / "game.asm"
BIN = ROOT / "sms" / "game.bin"
OUT = ROOT / "md_src" / "z80_sms_game.h"

# contract .DEFINEs exported to the 68K, asm name -> header name
EXPORT = {
    "TILEBUF":   "Z80_GAME_TILEBUF",
    "MAP_BITS":  "Z80_GAME_MAP_BITS",
    "MAP_META":  "Z80_GAME_MAP_META",
    "HEART":     "Z80_GAME_HEART",
    "PAD_MBX":   "Z80_GAME_PAD_MBX",
    "DIRTY_MBX": "Z80_GAME_DIRTY_MBX",
    "STATE_MBX": "Z80_GAME_STATE_MBX",
    "FRAME_MBX": "Z80_GAME_FRAME_MBX",
}

defines = {}
for line in ASM.read_text().splitlines():
    m = re.match(r"\.DEFINE\s+(\w+)\s+\$([0-9A-Fa-f]+)", line)
    if m:
        defines[m.group(1)] = int(m.group(2), 16)

missing = [k for k in EXPORT if k not in defines]
if missing:
    sys.exit(f"game.asm is missing contract .DEFINEs: {missing}")

data = BIN.read_bytes()
if len(data) != 0x2000:
    sys.exit(f"game.bin is {len(data)}B, expected 8192 (bad ROMBANKMAP?)")

end = len(data)
while end > 0 and data[end - 1] == 0:
    end -= 1
end += end & 1
blob = data[:end]

tilebuf = defines["TILEBUF"]
assert len(blob) <= tilebuf, (
    f"blob {len(blob)}B reaches into TILEBUF at ${tilebuf:04X}")

lines = [", ".join(f"0x{b:02X}" for b in blob[i:i + 12])
         for i in range(0, len(blob), 12)]
consts = "\n".join(f"#define {h} 0x{defines[a]:04X}"
                   for a, h in EXPORT.items())
OUT.write_text(
    "/* Auto-generated by tools/gen_z80_game.py — do not edit. */\n"
    "#ifndef Z80_SMS_GAME_H\n#define Z80_SMS_GAME_H\n"
    f"#define Z80_GAME_LEN {len(blob)}\n"
    "#define Z80_GAME_TILEBUF_ROWS 24\n"
    "#define Z80_GAME_TILEBUF_COLS 32\n"
    "#define Z80_GAME_TILEBUF_LEN 768\n"
    "#define Z80_GAME_MAP_LEN 132   /* 128B 1bpp map + spawn/exit meta */\n"
    f"{consts}\n"
    "static const unsigned char z80_sms_game[] = {\n    "
    + ",\n    ".join(lines)
    + "\n};\n#endif\n")
print(f"wrote {OUT.name}: {len(blob)}B blob, TILEBUF at ${tilebuf:04X}")
