#!/usr/bin/env python3
"""Codegen: registry.json "assets" -> sh_src/sprite_defs.h

Emits the data-driven sprite table the raycaster indexes by decal/standup kind,
so a new asset is added with a registry entry + its _tex.h and NO renderer edits
(the same move tools/gen_maps.py made for maps). The Makefile runs this whenever
registry.json or a referenced _tex.h changes.

  python3 tools/gen_assets.py
"""
import argparse, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

MOUNT  = {"wall": "SPRITE_MOUNT_WALL", "billboard": "SPRITE_MOUNT_BILLBOARD"}
DECODE = {"offset": "SPRITE_DECODE_OFFSET", "door": "SPRITE_DECODE_DOOR"}
FLAG   = {"animated": "SPRITE_F_ANIMATED", "lod": "SPRITE_F_LOD",
          "standalone": "SPRITE_F_STANDALONE"}


def die(m):
    sys.stderr.write("gen_assets: error: %s\n" % m)
    sys.exit(1)


def fxlit(v):
    s = ("%.4f" % float(v)).rstrip("0").rstrip(".")
    return "FX(%s)" % s


def emit(sprites):
    incl, seen = [], set()
    for s in sprites:
        for t in (s.get("tex"), s.get("tex_hi")):
            if t and t not in seen:
                seen.add(t); incl.append(t)

    L = ['/* AUTO-GENERATED by tools/gen_assets.py from registry.json "assets".',
         ' * Do NOT edit by hand; re-run the build to regenerate.',
         ' *',
         ' * The data-driven sprite table the raycaster indexes by kind. Add an asset',
         ' * with a registry.json "assets" entry + its _tex.h — no renderer edits. */',
         '#ifndef SPRITE_DEFS_H',
         '#define SPRITE_DEFS_H',
         '#include <stdint.h>',
         '#include "raycast.h"   /* fx_t, FX */']
    for t in incl:
        L.append('#include "%s"' % t)
    L += ['',
          '#define SPRITE_MOUNT_WALL      0   /* painted flat into the wall column */',
          '#define SPRITE_MOUNT_BILLBOARD 1   /* camera-facing free-standing standup */',
          '#define SPRITE_DECODE_OFFSET   0   /* 0 transparent, v>0 -> base + (v-1) */',
          '#define SPRITE_DECODE_DOOR     1   /* the door multi-ramp dlut */',
          '#define SPRITE_F_ANIMATED   0x01',
          '#define SPRITE_F_LOD        0x02   /* has a hi-res variant (tex_hi) */',
          '#define SPRITE_F_STANDALONE 0x04   /* free-standing (not wall-anchored) */',
          '',
          'typedef struct {',
          '    const uint8_t *tex, *tex_hi;       /* lo-res + optional hi-res (LOD) */',
          '    uint16_t w, h, w_hi, h_hi;         /* texture dims (0 hi if none) */',
          '    fx_t     world_h, world_hw, z;     /* world height, half-width, centre z */',
          '    uint8_t  base, mount, decode, flags;',
          '} sprite_def_t;',
          '',
          '/* Indexed by decal/standup kind (registry decals.kinds). */',
          'static const sprite_def_t sprite_defs[] = {']

    for s in sorted(sprites, key=lambda s: s["kind"]):
        sym, pfx = s["sym"], s["sym"].upper()
        if s.get("tex_hi"):
            symhi = s["sym_hi"]; phi = symhi.upper()
            texhi, whi, hhi = "(const uint8_t*)%s" % symhi, "%s_WIDTH" % phi, "%s_HEIGHT" % phi
        else:
            texhi, whi, hhi = "0", "0", "0"
        flags = " | ".join(FLAG[f] for f in s.get("flags", [])) or "0"
        L.append('    /* %-11s k%d */ { (const uint8_t*)%s, %s, %s_WIDTH, %s_HEIGHT, %s, %s, %s, %s, %s, %s, %s, %s, %s },' % (
            s["id"], s["kind"], sym, texhi, pfx, pfx, whi, hhi,
            fxlit(s["world_h"]), fxlit(s["world_hw"]), fxlit(s["z"]),
            s["base"], MOUNT[s["mount"]], DECODE[s["decode"]], flags))

    L += ['};', '',
          '#define SPRITE_DEF_COUNT (int)(sizeof sprite_defs / sizeof sprite_defs[0])',
          '#endif /* SPRITE_DEFS_H */', '']
    return "\n".join(L)


def validate(sprites):
    if not sprites:
        die("registry has no assets.sprites")
    kinds = {}
    for s in sprites:
        for k in ("id", "kind", "mount", "sym", "base", "decode"):
            if k not in s:
                die("%s: missing %r" % (s.get("id", "?"), k))
        if s["mount"] not in MOUNT:
            die("%s: unknown mount %r" % (s["id"], s["mount"]))
        if s["decode"] not in DECODE:
            die("%s: unknown decode %r" % (s["id"], s["decode"]))
        for f in s.get("flags", []):
            if f not in FLAG:
                die("%s: unknown flag %r" % (s["id"], f))
        if s["kind"] in kinds:
            die("kind %d used by both %s and %s" % (s["kind"], kinds[s["kind"]], s["id"]))
        kinds[s["kind"]] = s["id"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--registry", default=os.path.join(ROOT, "registry.json"))
    ap.add_argument("--out", default=os.path.join(ROOT, "sh_src", "sprite_defs.h"))
    args = ap.parse_args()
    with open(args.registry) as fh:
        sprites = json.load(fh).get("assets", {}).get("sprites", [])
    validate(sprites)
    text = emit(sprites)
    old = open(args.out).read() if os.path.exists(args.out) else None
    if old != text:
        with open(args.out, "w") as fh:
            fh.write(text)
    print("gen_assets: %d sprite(s) -> %s%s" %
          (len(sprites), args.out, "" if old != text else " (unchanged)"))


if __name__ == "__main__":
    main()
