#!/usr/bin/env python3
"""Round-trip editor kit for the PVM front-face texture (the bezel).

    export:  tools/pvm_bezel_edit.py export   -> sound-stage PNG, 8x scale
    import:  tools/pvm_bezel_edit.py import   -> regenerates pvm_front_tex.h

The PNG uses EXACT legend colors — paint with these and nothing else:

  BEZEL RAMP (case plastic, registry pvm pal, darkest -> lightest):
    value 1  rgb( 16, 16, 24)   near-black
    value 2  rgb( 48, 48, 56)   dark gray
    value 3  rgb(120,120,128)   mid gray
    value 4  rgb(168,168,176)   light gray
  SCREEN (functional regions — the engine owns what appears here):
    value 5  rgb(  0,255,  0)   GLASS CORE: static/telegraph/bloom paint here
    value 6  rgb( 64,  0, 64)   rim shade 1 (darkest curvature)
    value 7  rgb(128,  0,128)   rim shade 2
    value 8  rgb(192,  0,192)   rim shade 3
    value 9  rgb(255,  0,255)   rim shade 4 (lightest curvature)

Constraint: the glass REGION (values 5..9) can be reshaped a little, but
keep it roughly where it is — the telegraph capture resolution and the
CRT bloom read its bounding box (tg_scan_glass) at map load.
"""
import re, sys, pathlib

try:
    from PIL import Image
except ImportError:
    sys.exit("pip install pillow")

REPO = pathlib.Path(__file__).resolve().parent.parent
HDR = REPO / "sh_src" / "pvm_front_tex.h"
PNG = REPO / "pvm_bezel_edit.png"
SCALE = 8

LEGEND = {1: (16,16,24), 2: (48,48,56), 3: (120,120,128), 4: (168,168,176),
          5: (0,255,0), 6: (64,0,64), 7: (128,0,128), 8: (192,0,192),
          9: (255,0,255)}
RLOOK = {v: k for k, v in LEGEND.items()}

def read_header():
    t = HDR.read_text()
    w = int(re.search(r"PVM_FRONT_TEX_W (\d+)", t).group(1))
    h = int(re.search(r"PVM_FRONT_TEX_H (\d+)", t).group(1))
    vals = [int(x) for x in re.findall(r"\b(\d+)\b",
            t.split("= {", 1)[1].rsplit("};", 1)[0])]
    assert len(vals) == w * h, f"{len(vals)} vs {w*h}"
    return w, h, vals

def do_export():
    w, h, vals = read_header()
    im = Image.new("RGB", (w, h))
    im.putdata([LEGEND[v] for v in vals])
    im.resize((w * SCALE, h * SCALE), Image.NEAREST).save(PNG)
    print(f"wrote {PNG} ({w*SCALE}x{h*SCALE}, edit with the legend colors)")

def do_import():
    w, h, _ = read_header()
    im = Image.open(PNG).convert("RGB")
    assert im.size == (w * SCALE, h * SCALE), f"expected {w*SCALE}x{h*SCALE}"
    out = []
    for y in range(h):
        for x in range(w):
            px = im.getpixel((x * SCALE + SCALE // 2, y * SCALE + SCALE // 2))
            if px not in RLOOK:
                # nearest legend color: tolerate editor anti-alias slop
                px = min(RLOOK, key=lambda c: sum((a-b)**2 for a, b in zip(c, px)))
            out.append(RLOOK[px])
    rows = []
    for y in range(h):
        rows.append("    { " + ",".join(f"{v}" for v in out[y*w:(y+1)*w]) + " },")
    HDR.write_text(
        "/* Auto-generated by tools/pvm_bezel_edit.py (hand-edited bezel).\n"
        " * Box-face texture for sprite 'pvm': OPAQUE, values 1..4 ->\n"
        " * ramp_base + (v-1); 5 = glass core, 6..9 = rim. ROW-MAJOR. */\n"
        "#ifndef PVM_FRONT_TEX_H_INCLUDED\n#define PVM_FRONT_TEX_H_INCLUDED\n"
        "#include <stdint.h>\n"
        f"#define PVM_FRONT_TEX_W {w}\n#define PVM_FRONT_TEX_H {h}\n"
        f"static const uint8_t pvm_front_tex[PVM_FRONT_TEX_H][PVM_FRONT_TEX_W] = {{\n"
        + "\n".join(rows) + "\n};\n#endif /* PVM_FRONT_TEX_H_INCLUDED */\n")
    print(f"wrote {HDR}; run make")

if __name__ == "__main__":
    if len(sys.argv) != 2 or sys.argv[1] not in ("export", "import"):
        sys.exit(__doc__)
    (do_export if sys.argv[1] == "export" else do_import)()
